project_folder = "t_project_sno"

[environments.dev.connection]
type = "snowflake"
user = "mucio"
password = "env:SNOWFLAKE_PASSWORD"
role = "ACCOUNTADMIN"
warehouse = "SNOWFLAKE_LEARNING_WH"
database = "TEST_TEE"
host = "ZKYGKFY-WG80455.snowflakecomputing.com"
